spring:
  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
    consumer:
      group-id: aggregator-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: ru.practicum.ewm.stats.aggregator.serializer.UserActionAvroDeserializer
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: ru.practicum.ewm.stats.aggregator.serializer.EventSimilarityAvroSerializer

kafka:
  topics:
    user-actions: stats.user-actions.v1
    events-similarity: stats.events-similarity.v1

management:
  server:
    port: 9095
  endpoints:
    web:
      exposure:
        include: health,info,env
