spring:
  application:
    name: collector
  config:
    import: "optional:configserver:${CONFIG_SERVER_URI:http://localhost:8888}"

eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka/}
    registry-fetch-interval-seconds: 5
  instance:
    prefer-ip-address: true
    lease-renewal-interval-in-seconds: 5
    lease-expiry-duration-in-seconds: 15
